### PR TITLE
[FRAAS-23] Include link from Postman collection to desc of env variables

### PR DESCRIPTION
**Pull request by mjang**
This is the companion PR to [this PR on the dev docs](https://www.google.com/search?client=ubuntu&channel=fs&q=oauth+%22authentication+context%22&ie=utf-8&oe=utf-8)

Here's how the text would look (updated 8 Oct)

Screenshot from 2019-10-08 16-24-20

The link in the last visible line is intended to go to the new Postman Variables reference page

### CODE REVIEW

**Comment by mjang** [comment]
In addition, my checks suggest we can delete the following variables from our Postman environment (mostly because they're superseded by others):

* loginUrl
* logoutUrl
* emailTemplateId
* OneTimePasscode
* resetPasswordToken

**Comment by mjang** [comment]
I had to rebase because of

1) Merge conflicts
2) I forgot to sign my commit

If you've reviewed this and can rereview, I'd appreciate it! (note @forgerock-gina , I've incorporated your suggestion)

**Comment by mjang** [comment]
@janelleallen Thanks for the report. I've now fixed the issue, based on updating the Postman app to version 7.9.0. 

I've attached a video that
1) Checks out the PR branch (fraas-23/postmanVariables)
2) Imports the collection to the Postman App
3) Verifies the link to the list of Postman Variables

https://drive.google.com/file/d/1AL9wNlAGyvZv63YoClhGdOsTYvMomr8Q/view?usp=sharing

**Comment by janelleallen** [comment]
Hi Mike,  I upgrade postman, imported the collections again and it looks now.  I'm approving it now.  Thanks.

**Pull request merged**
