### PR TITLE
[FRAAS-463] Near comprehensive rewrite

### PR DESCRIPTION
**Pull request by mjang**
Update, July 1. Everything works! I've asked @markcraig to go through this from a Doc PoV (and he's more up to speed on OAuth2/OIDC thank I :))

To review this PR, I'd take the following steps: (My plan -- to set up this procedure in FRAAS-18)

0) Install Postman
1) Set up tenant, and log in (staging.forgeblocks.com)
1a) You'll need the tenant name, and the tenant access token from the dev console of your browser (it's associated with the session endpoint)
2) Download 
* 'ForgeRock Cloud APIs.postman_collection.json' (when you import it, you'll see it with a *(June 2019)* label
* 'ForgeRock Environment Vars 0.4.postman_environment.json'
3) Import files into Postman
4) Go into the environment (gear icon, upper right), and add
* tenant name
* access token
5) Compare text online, between two browsers:
* In your Postman app, find the arrow next to the collection, select "View in Web". That'll open up the web view in your default browser. (Or you can view it [here](https://cloud-forgerock.postman.co/collections/2524838-31f4f249-1e1c-4879-a416-4ad47bfa386b?version=latest&workspace=5533728c-a163-41f0-8d6d-ef9ea3d3cc4e))
(or if you have a space in our Postman Pro account, navigate to https://cloud-forgerock.postman.co/collections/2524838-0a6cda2f-98db-4a80-9c81-2af373e9db7e?version=latest&workspace=700e189a-c68e-4f6f-be16-bda221125d76 ) 
* In a second browser, navigate to developer-api.forgerock.com

Major changes:

1) I've made the calls more sequential. Example, under Management APIs / Apps / Web, you can run the commands sequentially, to demo create, update, regenerate secret, delete.
2) I've moved the Management APIs first, as some of those are prereqs to Authentication API calls.

### CODE REVIEW

**Comment by mjang** [comment]
NOTE: While I can continue work on this with the Docs73 tenant, I'm functionally blocked by FRAAS-683 (on the Docs74 tenant)

**Comment by markcraig** [comment]
Importing the collection and the environment works fine for me in the Postman standalone app on Linux. So does logging in to the tenant whose credentials you shared with me for testing.

I still cannot access the REST APIs due to some sort of DNS issue:

```
$ curl -v https://api-ui-docs79.forgeblocks.com/
* Could not resolve host: api-ui-docs79.forgeblocks.com
* Closing connection 0
curl: (6) Could not resolve host: api-ui-docs79.forgeblocks.com
```

**Comment by markcraig** [comment]
It would be really nice if the tenant admin UI offered a way to get at the admin access token.

Getting it out of the web developer tools in the browser is maybe okay for beta but seems like an "ease of use" blocker for GA.

**Comment by mjang** [comment]
Hi Mark, now I get it --

You were trying to connect to api-ui-docs79.forgeblocks.com

> ```bash
> curl -v https://api-ui-docs79.forgeblocks.com/
> ```

This works for me (and matches what's shown in the collection)

> ```bash
> curl -v https://api-docs79.forgeblocks.com/
> ```

**Comment by mjang** [comment]
Ack... I clicked the wrong button, and accidentally "re-requested" a review from @markcraig . My bad :)

**Comment by mjang** [comment]
> Comments:
> 
>     * Double-check the links. I got some 404s like https://developer-cloud.forgerock.com/quickstarts/password-policies/.

I've checked every link. If we continue to use Postman for our docs, I've added a quest for automation to FRAAS-609.

>     * Too bad you cannot run the API calls directly in the docs, even if you upload your environment. It seems like a limitation of Postman documents, 

That's one reason for me to pursue https://forgerock-demo.redoc.ly/ (forgerock/demo)

>     * `{{userName}}` defaults to `bjensen@example.com`. Should `{{user_id}}` default to `bjensen`?

I've checked -- not in the original version of the 0.4 environment. Only after you create a user does {{userName}} get set to the new user, in this case, `bjensen@example.com`
 
>     * Might want to review the environment variables for consistency. Sometimes you use underscores_in_names, other times camelCase.

Absolutely. A post-beta task for me. I think also I have a few excess variables.

**Comment by markcraig** [comment]
Thanks, Mike. LGTM.

**Comment by mjang** [comment]
> Hi Mike, I think this is a big improvement and like better where the collection is going. I was attempting to get through the PKCE Auth code flows. I noticed a couple of things:
> 
> Pre-req is that you need to create a user and in doing that they need to get an m2m token 

Did we want to apply PKCE flows to Service( m2m) apps? That would be new. 

> which then sets a var called appAccessToken. However the var being used in the collection is just accessToken. 

I realize I have some "cleanup" to do w/r/t variables. I've hard coded too many things. I set that task aside to work on other pre-beta doc tasks. 

> It would be slightly more convenient if that was setting appAccessToken and then denoting it in the console like Acquired session is output in the console on the authenticate endpoint. Maybe something like "Setting accessToken to " in the test script. I did run into a roadblock on the authorization code flow getting error: {
> description: "The redirection URI provided does not match a pre-registered value.",
> message: "redirect_uri_mismatch"

I'm guessing this error -- at least w/r/t Native/SPA apps, is based on the difference between http://localhost:9080/* and https://example.com/homeLogin as login URIs (based on Gemma's advice). When I use example.com, it makes for better screenshots -- (try example.com in Chrome, and I think you'll see what I mean).

> Despite having set a redirect url to http://localhost:9080. in the spa app. Not sure if this is due to the upgrade to 7.0 or not since this is a new tenant.
> 
> I noticed the vars contain a var for spaAppClientSecret because spa apps don't ever have secrets I think it should be removed from the vars

Perhaps that's still a bug -- I get a client secret when I run the REST call to regenerate client secrets for SPA apps.

> 
> Also, I noticed spaclient was used for the PKCE collection. I would assume this could possibly be for native apps as well and perhaps even web apps using a PKCE flow. I don't know if we could use a more generic term for clientid perhaps just clientid and denote this can be used for either spa/native or web flows. 

As discussed with Jared, I have two different flows for Native/SPA PKCE and Web App PKCE, based on James P's guidance in FRAAS-458. So I want different client IDs for different types of apps

> James P should be able to confirm if this can be used for web flows too difference being web flows would have a secret. 

As described by James P in FRAAS-458, and discussed with Jared. (I'm in the middle of drafting the flow for the main docs -- but I need a working tenant to confirm the process.)
 
> Anyhow, I can't say I can get the token in the end right now perhaps we can review together

I know I was having problems this morning with PKCE flows that were working all last week.

**Comment by mjang** [comment]
Merging after discussion with @janelleallen

**Pull request merged**
